{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "qwery-ai.fullname" . }}
  labels:
    {{- include "qwery-ai.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "qwery-ai.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- toYaml .Values.networkPolicy.ingress | nindent 2 }}
  egress:
  {{- toYaml .Values.networkPolicy.egress | nindent 2 }}
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
{{- end }}
