apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-pgvector.fullname" . }}-secret
  labels:
    {{- include "postgresql-pgvector.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.username }}
  password: {{ .Values.postgresql.password }}
  postgres-password: {{ .Values.postgresql.postgresPassword }}
  database: {{ .Values.postgresql.database }}
